In [4]:
import pandas as pd
import numpy as np

## 1

In [10]:
a=[
    [[23,50],[7,12]],
    [[57,67],[99,43]],
    [[75,21],[57,12]],
    [[87,26],[18,84]]
]


In [11]:
s=np.array(a)

In [12]:
s

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [16]:
s.shape

(4, 2, 2)

In [13]:
Tensor=np.array(
        [
        [[1,0,2],[2,5,4],[1,1,1]],
        [[6,7,1],[0,2,4],[7,8,1]],
        [[1,1,3],[4,5,1],[2,3,7]]
        ]
)

In [14]:
Tensor

array([[[1, 0, 2],
        [2, 5, 4],
        [1, 1, 1]],

       [[6, 7, 1],
        [0, 2, 4],
        [7, 8, 1]],

       [[1, 1, 3],
        [4, 5, 1],
        [2, 3, 7]]])

## 2

In [43]:
a=[[23,59,19],[7,12,109],[57,67,98]]
b=[[17,22,19]]

In [44]:
A=np.array(a)
B=np.array(b)

In [46]:
A

array([[ 23,  59,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [45]:
B

array([[17, 22, 19]])

In [47]:
A*B

array([[ 391, 1298,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

## 3.

In [48]:
A.transpose()

array([[ 23,   7,  57],
       [ 59,  12,  67],
       [ 19, 109,  98]])

In [49]:
np.linalg.det(A)

181086.9999999999

In [50]:
np.linalg.inv(A)

array([[-0.03383457, -0.02489963,  0.03425425],
       [ 0.03052124,  0.00646651, -0.01310972],
       [-0.00118727,  0.01006146, -0.00075654]])